spring:
  application:
    name: UserSystem
  profiles:
    active: dev
#  autoconfigure:
#    exclude:


  mail:
    # 发送者邮箱
    username: l2292360909@163.com
    #申请到的授权码
    password: BMwJvQVRj3yEVjuk
    # 配置 SMTP 服务器地址
    host: smtp.163.com
    # 端口号465或587
    port: 465
    protocol: smtps
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
          debug: true
          ssl: true


server:
  servlet:
    context-path: /api
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false
app:
  name: UserSystem
